logging:
  file:
    name: 'myapp-log'
    path: '~/log'


spring:
  datasource:
    url: jdbc:h2:file:/home/kiyoung/h2db/sessionUser
    username: user
    password: password

  h2:
    console:
      path: /h2-console
      enabled: true

  jpa:
    generate-ddl: true
    hibernate:
      default_batch_fetch_size: 100
      ddl-auto: update
    open-in-view: false
    show-sql: true

  mvc:
    view:
      suffix: ".html"