logging:
  file:
    name: 'myapp-log'
    path: '~/log'


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testDB?serverTimezone=Asia/Seoul&createDatabaseIfNotExist=true
    username: kiyoung
    password: 0412Rlarud!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    generate-ddl: true
    hibernate:
      default_batch_fetch_size: 100
      ddl-auto: create
    open-in-view: false
    show-sql: true

  mvc:
    view:
      suffix: ".html"