spring:
  datasource:
    url: jdbc:mysql://${mysql_address}:3306/testDB?serverTimezone=Asia/Seoul&createDatabaseIfNotExist=true
    username: ${mysql_username}
    password: ${mysql_password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    generate-ddl: true
    hibernate:
      default_batch_fetch_size: 100
      ddl-auto: create
    open-in-view: false
    show-sql: true

  mvc:
    view:
      suffix: ".html"

server:
  tomcat:
    accesslog:
      enabled: true
      pattern: "%{X-Forwarded-For}i %l %u %{YYYY-MM-DD}t %r %s %b"
      max-days: 30
      directory: ./log

